---
abstract: 'A Task module for DWIM Perl L<http://dwimperl.com/>'
author:
  - 'Gabor Szabo <szabgab@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-DWIM-Dancer
no_index:
  directory:
    - inc
    - t
requires:
  Dancer: 1.3092
  Dancer::Plugin::Auth::RBAC: 1.110720
  Dancer::Plugin::Auth::Twitter: 0.02
  Dancer::Plugin::Captcha::SecurityImage: 0.10
  Dancer::Plugin::DBIC: 0.1601
  Dancer::Plugin::Database: 2.03
  Dancer::Plugin::FlashMessage: 0.314
  Dancer::Plugin::SimpleCRUD: 0.80
  Dancer::Plugin::SiteMap: 0.11
  perl: 5.008
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/dwimperl/Task-DWIM
version: 0.06
